# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zip_upload' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for zip_upload

pod 'Zip', '~> 1.1'
pod 'Alamofire', '~> 4.7'

end
