# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'login_ChinaAirline_swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'Kanna', '~> 4.0.0'

  # Pods for login_ChinaAirline_swift

end
