project 'Demo5.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo5' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'CryptoSwift', '~> 0.8'
  pod 'Alamofire', '~> 4.0'
  pod 'ReachabilitySwift', '~> 4.0'

end
